Feat/14
survey-mate/backend pull request #15
Opened 2024-01-11 12:57 UTC by mingmingmon

DB 엔티티와 프로젝트 구조 틀 구현했습니다.

DTO는 아직 구현을 안 한 상태입니다. 각자 API 만들면서 본인 스타일대로 만드는 것도 괜찮고
지금 구현된 엔티티 쪽 피드백 받고 나서 제가 구현해도 괜찮습니다.

확인해보시고 코멘트 달아주세요!

2024-01-11 14:23 UTC, JinhyeokFang requested changes

2024-01-11 14:23 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/survey/Survey.java
> +    private LocalDateTime estimatedTime;
이 부분은 ```@Timestamp```를 빼도 괜찮아요
예상 시간을 저장하는 거니까 LocalTime 타입이 더 알맞을 거 같아요!

2024-01-11 14:23 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/answer/Answer.java
> +@NoArgsConstructor
엔티티에서 ```@Setter```사용은 최대한 안하는 게 좋을 것 같아요! (private 필드를 선언하는 의미가 없어집니다)
생성자도 protected로 바꾸면 캡슐화에 더 좋습니다 ```@NoArgsConstructor(access = AccessLevel.PROTECTED)```

2024-01-11 14:24 UTC, JinhyeokFang commented
포트 번호 8080번으로 롤백 부탁드립니다!

2024-01-12 12:07 UTC, mingmingmon commented
진혁님 피드백 수정 완료했습니다!

2024-01-13 03:16 UTC, JinhyeokFang approved these changes
LGTM

2024-01-13 08:26 UTC, Sanghyunn approved these changes
머지하셔도 될거 같습니다!

2024-01-14 04:50 UTC, merged