feat: API 공통 응답 추가 #21
survey-mate/backend pull request #22
Opened 2024-01-17 05:54 UTC by mingmingmon

api 공통 응답 만들었습니다!

부족한 부분이 많이 있을 것 같은데 확인해주세요! 

공통 응답은 제가 만들어본 적이 없어서 뭐가 더 좋고 선호하는지 잘 몰라서
아니면 다른 형식으로 진행하고 싶으시면 아예 틀 말씀해주셔도 됩니다!

2024-01-17 06:03 UTC, JinhyeokFang requested changes
이 부분만 구현해주시면 될 거 같습니다!

2024-01-17 06:03 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/common/response/ApiResponse.java
> +   /* public static <T> ApiResponse<T> onSuccess(T result){
성공인 경우도 구현해주세요!

2024-01-17 06:03 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/common/response/ApiResponse.java
> +    public static <T> ApiResponse<T> onFailure (String status, String message, Object data){
data 타입 Object말고 제너릭 사용해주세요

2024-01-17 14:01 UTC, Sanghyunn approved these changes

2024-01-19 11:56 UTC, JinhyeokFang approved these changes

2024-01-19 11:56 UTC, merged