Feat: 비밀번호 재설정, 비밀번호 변경 API 작성
survey-mate/backend pull request #40
Opened 2024-01-25 05:49 UTC by mingmingmon

2024-01-25 06:18 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/PasswordUpdateRequestDTO.java
> +    private String currPassword;
약자는 최대한 지양해주세요!
```currPassword -> currentPassword```

2024-01-25 06:18 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/common/auth/AuthProvider.java
> +            throw new GeneralException(Status.NO_AUTH);
```NO_AUTH -> UNAUTHENTICATED_USER```

2024-01-25 06:18 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/CertificateCodeRequestDTO.java
> +package uk.jinhy.survey_mate_api.auth.presentation.dto;
DTO 파일 개별로 만들지 말고 하나로 합쳐주세요
SurveyControllerDTO를 참고해주세요

2024-01-25 06:18 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/common/config/SecurityConfig.java
> +    private final UserDetailsServiceImpl userDetailsServiceImpl;
구현체와 정의를 분리하실거면 UserDetailsServiceImple을 주입받는 것이 아니라 UserDetailsService를 주입 받으셔야 합니다!
변수 이름도 userDetailsService로 바꿔주세요

2024-01-25 06:18 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/jwt/CustomAuthenticationProvider.java
> +        User user = null;
변수에 null을 넣어서 초기화하는 건 최대한 피해주세요!

2024-01-25 08:15 UTC, Sanghyunn approved these changes

2024-01-25 13:25 UTC, JinhyeokFang requested changes
리뷰 확인 부탁드립니다!

2024-01-25 13:25 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/AuthControllerDTO.java
> +    public static class LoginControllerDTO {
1. ```LoginControllerDTO```라고 이름지으신 이유를 알 수 있을까요? ```LoginController```가 없는데 ```LoginControllerDTO```는 있어서 이유가 궁금합니다!
2. AuthControllerDTO가 AuthController가 아닌 다른 컨트롤러의 DTO를 담을 필요는 없을 것 같습니다.

2024-01-25 13:25 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/application/service/MailService.java
Mail은 인증(Auth)과 다른 기능입니다. 패키지를 분리하는 편이 더 유연할 것 같습니다!

2024-01-25 13:25 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/domain/entity/PasswordResetCode.java
> +@AllArgsConstructor(access = AccessLevel.PROTECTED)
```NoArgsConstructor```를 Protected로 하는 이유는 JPA만 Argument가 없는 생성자를 사용하도록 하기 위함입니다. 
(JPA의 기술적 문제로 Private 생성자를 사용할 수 없습니다. JPA는 사용자가 구현한 Entity를 상속받아 코드를 구현합니다. -> Protected인 이유)
```AllArgsConstructor```는 Public을 쓰거나 Private을 쓰는 것이 더 적절한 것 같습니다.

2024-01-25 13:25 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/domain/repository/PasswordResetTokenRepository.java
> +
줄바꿈은 특별한 경우가 아니라면 한 번만 해주세요.

2024-01-25 13:25 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
> +    @PostMapping("/password/reset")
Post보단 Put이나 Patch가 더 적절합니다.

2024-01-25 13:25 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
>                  Status.OK.getMessage(), result);
1. result는 변수의 값을 이해하는데 적절한 이름은 아닌 것 같습니다!
2. service의 값을 바로 리턴하지 말고 dto를 만들어서 리턴해주세요.
(
클라이언트 쪽에서 결과를 받을때
결과: ``` [문자열] ```
보다는
결과: ``` { code: [문자열] } ```
가 더 이해하기 쉽습니다.
)

2024-01-25 13:25 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
> +                Status.OK.getMessage(), memberId + "계정의 비밀번호가 수정되었습니다.");
상태 코드가 200이므로 Body에 넣어서 전달하는 문자열은 무의미한 데이터입니다.

2024-01-25 13:28 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/AuthControllerDTO.java
> +        private String title;
mailSubject로 하시려면 여기도 mailTitle로 바꿔주시면 좋을 것 같습니다.
반대로 mailSubject -> subject도 괜찮습니다!

2024-01-26 14:11 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
>          if(isExist){
```
boolean isExist = memberRepository.existsByMemberId(memberId);
        if(isExist){
```
if문 공백 띄워주세요

2024-01-26 14:12 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
>          LocalDateTime currTime = LocalDateTime.now();
currTime -> currentTime 또는 now

2024-01-26 14:14 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
> +        if(!passwordResetTokenRepository.existsByEmailAddressAndToken(emailAddress, resetToken)){
```
// X
if(!passwordResetTokenRepository.existsByEmailAddressAndToken(emailAddress, resetToken)){
// O
if (!passwordResetTokenRepository.existsByEmailAddressAndToken(emailAddress, resetToken)) {
```
위 코드에선 isExist 변수를 만들어서 조건을 검사하셨는데
여기에서는 조건식이 inline화 되어있습니다.
한 쪽으로 통일해주시면 더 좋을 것 같습니다!

2024-01-26 14:15 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
> +        String currPassword = requestDto.getCurrentPassword();
currPassword -> currentPassword
**약자 사용하지 말아주세요**

2024-01-26 14:16 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/application/service/AuthService.java
> +        Member modifiedMember = Member.builder()
굳이 엔티티를 새로 만들 필요는 없을 것 같아요!
불러온 엔티티 가지고 member.changePassword()로 도메인 영역 로직을 호출하고
repository에 저장하는 것이 더 간단할 것 같습니다!

2024-01-26 14:18 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/presentation/AuthController.java
> +        return ApiResponse.onSuccess(Status.CREATED.getHttpStatus().toString(),
```
return ApiResponse.onSuccess(Status.OK.getCode(), Status.OK.getMessage() //...
```

2024-01-26 14:18 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/auth/presentation/dto/AuthControllerDTO.java
> +        private String id;
DTO 부분 줄바꿈 모두 통일해주세요.

2024-01-26 14:20 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/common/util/CreateCodeUtil.java
> +        int length = 6;
length는 파라미터로 받아주세요. (length가 바뀌어도 로직이 변경되지 않기 때문에 코드가 더 유연해집니다.)

2024-01-27 02:22 UTC, JinhyeokFang approved these changes

2024-01-27 02:22 UTC, merged