feat: 설문장터 API Controller 부분 구현
survey-mate/backend pull request #42
Opened 2024-01-26 17:50 UTC by Sanghyunn

다음과 같은 부분을 구현했습니다
- Controller API 부분 구현
- 업로드한 데이터 파일 S3에 저장

2024-01-27 02:34 UTC, JinhyeokFang requested changes

2024-01-27 02:34 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/common/aws/S3Service.java
> +    @Autowired
주입은 생성자로 해주세요!
[https://sanghoonly.tistory.com/101](https://sanghoonly.tistory.com/101)

2024-01-27 02:34 UTC, JinhyeokFang commented on src/main/java/uk/jinhy/survey_mate_api/common/config/S3Config.java
> +@Getter
secretKey 같이 S3Config 외부에 노출되면 안되는 값이 있는 경우엔 @Getter를 빼고 직접 Getter를 만들어주세요.

2024-01-27 10:10 UTC, JinhyeokFang approved these changes

2024-01-28 04:58 UTC, mingmingmon approved these changes

2024-01-28 04:58 UTC, merged